[project]
name = 'Supply-Chain-Tracking'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.supply-chain-tracking]
path = 'contracts/supply-chain-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
